/**
 * Initializes all Flight Software Components and Tasks
 */

#pragma once

#include <stdbool.h>

#include "stm32f4xx_hal.h"

typedef struct {
    UART_HandleTypeDef* p_huart1;
} SystemHardwareHandles_t;

/**
 * @brief Initializes all FSW Components
 * @param hardwareHandles - A struct containing pointers to all hardware handles generated by CubeMX in main
 * @returns True on success, False otherwise
 */
bool SystemInitializer_Init(SystemHardwareHandles_t hardwareHandles);

/**
 * @brief Starts the FSW by creating all tasks and starting the RTOS kernel
 */
void SystemInitializer_Start();

/**
 * @brief Stops the FSW and cleans up remaining resources
 */
void SystemInitializer_Stop();